defter/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, UpdateView, CreateView
from core.forms import CompanyForm
from core.models import CompanyLine, Company
from core.views import CompanyListView, CompanyDetailView, CompanyLineCreateView, \
    UserCreateView, CompanyLineUpdateView, CompanyListOverlimitView, CompanyUpdateView, CompanyCreateView, \
    CompanyQueryView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', login_required(CompanyListView.as_view()), name='home'),
    url(r'^company/list/overlimit$', login_required(CompanyListOverlimitView.as_view()), name='company-list-overlimit'),
    url(r'^company/list/(?P<capital>.*)$', login_required(CompanyListView.as_view()), name='company-list-letter'),
    url(r'^company/query/$', login_required(CompanyQueryView.as_view()), name='company-query'),
    url(r'^company/add/$', login_required(CompanyCreateView.as_view()), name='company-create'),
    url(r'^company/(?P<pk>\d+)/edit', login_required(CompanyUpdateView.as_view(model=Company, form_class=CompanyForm)), name='company-edit'),
    url(r'^company/(?P<pk>\d+)$', login_required(CompanyDetailView.as_view()), name='company-detail'),
    url(r'^company/line/(?P<pk>\d+)/add', login_required(CompanyLineCreateView.as_view()), name='company-line-create'),
    url(r'^company/line/(?P<pk>\d+)/edit', login_required(CompanyLineUpdateView.as_view()), name='company-line-edit'),
    url(r'^company/line/(?P<pk>\d+)$', login_required(DetailView.as_view(model=CompanyLine, context_object_name='line')), name='company-line-detail'),

    url(r'^accounts/create/$', login_required(UserCreateView.as_view()), name='user-create'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    # url(r'^defter/', include('defter.foo.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

core/models.py
# coding=utf-8
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    phone = models.CharField(max_length=128)

    def __unicode__(self):
        return u'%s' % (self.user.username,)


class Company(models.Model):
    owner = models.ForeignKey(UserProfile, blank=True, related_name='owned_companies')
    name = models.CharField(max_length=255, verbose_name=u'Şirket adı')
    address = models.TextField(max_length=512, null=True, blank=True, verbose_name=u'Adres')
    phone = models.CharField(max_length=128, null=True, blank=True, verbose_name=u'Şirket telefonu')
    limit = models.IntegerField(null=True, blank=True, verbose_name=u'Uyarı limiti')
    vergidairesi = models.CharField(null=True, blank=True, max_length=128, verbose_name=u'Vergi Dairesi')
    vergino = models.CharField(max_length=20, null=True, blank=True, verbose_name=u'Vergi Numarası')
    fax = models.CharField(max_length=128, null=True, blank=True,verbose_name=u'Fax')
    email = models.EmailField(blank=True, null=True)
    def get_absolute_url(self):
        return reverse('company-detail', kwargs={'pk': self.pk})

    def __unicode__(self):
        return self.name

TIP_CHOICES = (
    ('N', 'Nakit',),
    ('S', 'Senet',),
    ('C', 'Çek',),
    ('P', 'Pos',),
)

class CompanyLine(models.Model):
    is_cancelled = models.BooleanField(default=False, blank=True, verbose_name=u'İptal Mi')
    company = models.ForeignKey(Company, related_name='lines', verbose_name=u'Şirket')
    borc = models.IntegerField(null=True, blank=True, default=0, verbose_name=u'Borç')
    alacak = models.IntegerField(null=True, blank=True, default=0, verbose_name=u'Alacak')
    note = models.CharField(max_length=1024, blank=True, null=True, verbose_name=u'Not')
    tip = models.CharField(max_length=20, verbose_name=u'Tip', default='N', choices=TIP_CHOICES)
    created_at = models.DateField(verbose_name=u'Oluşturulma Tarihi')
    created_by = models.ForeignKey(UserProfile, related_name='created_by', verbose_name=u'Oluşturan')
    modified_at = models.DateTimeField(blank=True, null=True, verbose_name=u'Değiştirilme Tarihi')
    modified_by = models.ForeignKey(UserProfile, null=True, blank=True, related_name='modified_by', verbose_name=u'Değiştiren')

    def get_absolute_url(self):
        return reverse('company-line-detail', kwargs={'pk':self.pk})

    def __unicode__(self):
        return u"borc: %d, alacak: %d" %(self.borc, self.alacak,)


def create_user_profile(sender, instance, created, **kwargs):
    """Create the UserProfile when a new User is saved"""
    if created:
        profile = UserProfile()
        profile.user = instance
        profile.save()

post_save.connect(create_user_profile, sender=User)

core/forms.py
# coding=utf-8
from django import forms, contrib
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from core.models import CompanyLine, Company, UserProfile

__author__ = 'idursun'

class CompanyLineForm(forms.ModelForm):
    borc_tam = forms.IntegerField(min_value=0)
    borc_kusur = forms.IntegerField(min_value=0, max_value=100)
    alacak_tam = forms.IntegerField(min_value=0)
    alacak_kusur = forms.IntegerField(min_value=0, max_value=100)
    created_at = forms.DateField(input_formats=('%d/%m/%Y','%d-%m-%Y',))

    class Meta:
        model = CompanyLine
        exclude = ('created_by','modified_by', 'modified_at', 'company', 'borc', 'alacak',)


class CompanyForm(forms.ModelForm):
    limit_tam = forms.IntegerField(min_value=0)
    limit_kusur = forms.IntegerField(min_value=0, max_value=99)

    class Meta:
        model = Company
        exclude = ('limit','owner',)

class UserCreateForm(contrib.auth.forms.UserCreationForm):
    email = forms.EmailField()

core/views.py
# coding=utf-8
from datetime import datetime
from dateutil.relativedelta import relativedelta
from django.core.paginator import Paginator, EmptyPage
from django.core.urlresolvers import reverse_lazy
from django.db.models import Sum, Q
from django.views.generic import TemplateView, CreateView, UpdateView
from core.forms import CompanyLineForm, CompanyForm, UserCreateForm
from core.models import Company, CompanyLine, UserProfile

class CompanyListView(TemplateView):
    template_name = 'core/company_list.html'

    def get_context_data(self, **kwargs):
        userprofile = self.request.user.get_profile()
        companies = userprofile.owned_companies.annotate(sum_borc=Sum('lines__borc'), sum_alacak=Sum('lines__alacak'))
        if 'capital' in kwargs:
            capital = kwargs.pop('capital')
            q = None
            letters = u"0123456789"
            if capital == '09':
                letters = u"0123456789"
            if capital == 'AD':
                letters = u"ABCÇçD"
            if capital == 'EH':
                letters = u"EFGH"
            if capital == 'IL':
                letters = u"IİiJKL"
            if capital == 'MP':
                letters = u"MNOÖP"
            if capital == 'RT':
                letters = u"RSŞşT"
            if capital == 'UZ':
                letters = u"UÜüVYXZ"

            for letter in letters:
                if q is None:
                    q = Q(name__istartswith=letter)
                else:
                    q |= Q(name__istartswith=letter)

            companies = companies.filter(q)
        context = super(CompanyListView, self).get_context_data(**kwargs)
        context.update({
            'companies': companies,
            'letters': [
                ("09", "0-9"),
                ("AD", "ABCÇD"),
                ("EH", "EFGĞH"),
                ("IL", "IİJKL"),
                ("MP", "MNOÖP"),
                ("RT", "RSŞT"),
                ("UZ", "UÜVYXZ"),
            ],
        })
        return context


class CompanyListOverlimitView(TemplateView):
    template_name = 'core/company_list.html'

    def get_context_data(self, **kwargs):
        userprofile = self.request.user.get_profile()
        companies = userprofile.owned_companies.annotate(sum_borc=Sum('lines__borc'), sum_alacak=Sum('lines__alacak'))
        for company in companies:
            if company.sum_borc is None:
                company.sum_borc = 0
            if company.sum_alacak is None:
                company.sum_alacak = 0
        over_limit = [company for company in companies if
                      not company.limit is None and company.limit < company.sum_borc - company.sum_alacak]
        context = super(CompanyListOverlimitView, self).get_context_data(**kwargs)
        context.update({
            'companies': over_limit,
        })
        return context


class CompanyCreateView(CreateView):
    model = Company
    form_class = CompanyForm

    def form_valid(self, form):
        form.instance.owner = self.request.user.get_profile()
        form.instance.limit = form.cleaned_data['limit_tam'] * 100 + form.cleaned_data['limit_kusur']
        return super(CompanyCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('company-detail', args=(self.object.pk,))


class CompanyUpdateView(UpdateView):
    model = Company
    form_class = CompanyForm

    def form_valid(self, form):
        form.instance.limit = form.cleaned_data['limit_tam'] * 100 + form.cleaned_data['limit_kusur']
        return super(CompanyUpdateView, self).form_valid(form)

    def get_initial(self):
        initial = super(CompanyUpdateView, self).get_initial()
        if self.object.limit is None:
            self.object.limit = 0
        initial['limit_tam'] = int(self.object.limit / 100)
        initial['limit_kusur'] = int(self.object.limit % 100)
        return initial


class CompanyDetailView(TemplateView):
    template_name = 'core/company_detail.html'

    def get_context_data(self, **kwargs):
        context = super(CompanyDetailView, self).get_context_data(**kwargs)
        curr_page_no = 1

        get_queries = self.request.GET.copy()
        if 'page' in get_queries:
            curr_page_no = int(get_queries['page'])
            del get_queries['page']

        company = Company.objects.get(pk=kwargs.pop('pk') or 1)
        lines = CompanyLine.objects.filter(company=company)

        start_date = None
        end_date = None

        if 'start_date' in self.request.GET:
            try:
                start_date = datetime.strptime(self.request.GET.get('start_date'), "%d/%m/%Y")
                lines = lines.filter(created_at__gte=start_date)
            except ValueError:
                pass
        if 'end_date' in self.request.GET:
            try:
                end_date = datetime.strptime(self.request.GET.get('end_date'), "%d/%m/%Y")
                lines = lines.filter(created_at__lte=end_date)
            except ValueError:
                pass

        lines = lines.order_by('created_at')
        paginator = Paginator(lines, 25)
        next_page_no = None
        prev_page_no = None
        try:
            page = paginator.page(curr_page_no)
        except EmptyPage:
            curr_page_no = 1
            page = paginator.page(1)

        if page.has_next():
            next_page_no = curr_page_no + 1

        if page.has_previous():
            prev_page_no = curr_page_no - 1

        total = 0
        for i, line in enumerate(page):
            line.no = (curr_page_no - 1) * 10 + i + 1
            total += line.borc - line.alacak
            line.total = total

        context.update({
            'paginator': paginator,
            'company': company,
            'curr_page_no': curr_page_no,
            'prev_page_no': prev_page_no,
            'next_page_no': next_page_no,
            'lines': page,
            'start_date': start_date,
            'end_date': end_date,
            'queries': get_queries
        })
        return context


class CompanyLineCreateView(CreateView):
    model = CompanyLine
    form_class = CompanyLineForm

    def get_initial(self):
        initial = super(CompanyLineCreateView, self).get_initial()
        initial['created_at'] = datetime.now()
        return initial

    def get_context_data(self, **kwargs):
        context = super(CompanyLineCreateView, self).get_context_data(**kwargs)
        context.update({
            'company': Company.objects.get(pk=self.kwargs.pop('pk'))
        })
        return context


    def form_valid(self, form):
        userprofile, result = UserProfile.objects.get_or_create(user=self.request.user)
        form.instance.company = Company.objects.get(pk=self.kwargs.pop('pk'))
        form.instance.created_by = userprofile
        form.instance.borc = form.cleaned_data['borc_tam'] * 100 + form.cleaned_data['borc_kusur']
        form.instance.alacak = form.cleaned_data['alacak_tam'] * 100 + form.cleaned_data['alacak_kusur']
        form.instance.created_at = form.cleaned_data['created_at']
        return super(CompanyLineCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('company-detail', args=(self.object.company_id,))


class CompanyLineUpdateView(UpdateView):
    model = CompanyLine
    form_class = CompanyLineForm

    def get_initial(self):
        initial = super(CompanyLineUpdateView, self).get_initial()
        initial['borc_tam'] = int(self.object.borc / 100)
        initial['borc_kusur'] = int(self.object.borc % 100)
        initial['alacak_tam'] = int(self.object.alacak / 100)
        initial['alacak_kusur'] = int(self.object.alacak % 100)
        initial['created_at'] = self.object.created_at
        return initial

    def get_context_data(self, **kwargs):
        context = super(CompanyLineUpdateView, self).get_context_data(**kwargs)
        context.update({
            'company': Company.objects.get(pk=self.object.company_id)
        })
        return context

    def form_valid(self, form):
        self.object.modified_by = self.request.user.get_profile()
        self.object.modified_at = datetime.now()
        self.object.borc = form.cleaned_data['borc_tam'] * 100 + form.cleaned_data['borc_kusur']
        self.object.alacak = form.cleaned_data['alacak_tam'] * 100 + form.cleaned_data['alacak_kusur']
        return super(CompanyLineUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('company-detail', args=(self.object.company_id,))


class UserCreateView(CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('home')
    template_name = 'core/user_form.html'

class CompanyQueryView(TemplateView):
    template_name = 'core/company_query.html'

    def get_context_data(self, **kwargs):
        context = super(CompanyQueryView, self).get_context_data(**kwargs)
        start_date = datetime.now() - relativedelta(months=1)
        end_date = datetime.now()
        if 'start_date' in self.request.GET:
            start_date = datetime.strptime(self.request.GET.get('start_date'), "%d/%m/%Y")
        if 'end_date' in self.request.GET:
            end_date = datetime.strptime(self.request.GET.get('end_date'), "%d/%m/%Y")

        query = list(CompanyLine.objects.filter(created_at__gte=start_date, created_at__lte=end_date).values(
            'company__owner').annotate(sum_borc=Sum('borc'), sum_alacak=Sum('alacak')))
        for line in query:
            line['owner'] = UserProfile.objects.get(pk=line['company__owner'])
        context.update({
            'lines': query,
            'query': u"?start_date={0}&end_date={1}".format(start_date.strftime("%d/%m/%Y").encode(),

defter/templates/core/company_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <form method="POST" action="">
        {% csrf_token %}
        <p>Şirket: {{ object.name }}</p>
        <p><strong>Bu şirketi silmek istediğinize emin misiniz?</strong></p>
        <button type="submit" class="btn btn-primary">Evet</button>
        <a class="btn" href="{% url home %}">Hayır</a>
    </form>

{% endblock %}

defter/templates/core/company_detail.html
{% extends 'base.html' %}
{% load defter_filters %}
{% block content %}
    <script>
    function send() {
        var start = $("#id_start_date").val();
        var end = $("#id_end_date").val();
        window.location.replace("?start_date=" + start + "&end_date=" + end);
    }
    </script>

    <div class="row">

        <div class="row">
            <a class="btn" href="{% url company-line-create company.id %}">Yeni Giriş</a>
            <a class="btn" href="{% url company-edit company.id %}">Şirket Bilgilerini Güncelle</a>
            Başlangıç
            <input class="span2 datepicker" type="text" id="id_start_date"  name="start_date" value="{{ start_date|date:"d/m/Y" }}" />
            <span>Bitiş</span>
            <input class="span2 datepicker" type="text" id="id_end_date" name="end_date" value="{{ end_date|date:"d/m/Y" }}" />
            <button class="btn btn-primary" type="submit" onclick="send()">Listele</button>
        </div>

        <div class="row">
            <span class="span12"><strong>{{ company.name }}</strong></span>
        </div>
        <div class="row">
            <span class="span12"></span><span class="span8">{{ company.address }}</span>
        </div>
        <div class="row">
            <span class="span2">E-Posta:</span><span class="span3">{{ company.email|default_if_none:"" }}</span>
        </div>
        <div class="row">
            <span class="span2">Vergi Dairesi:</span><span class="span3">{{ company.vergidairesi|default_if_none:"" }}</span>
        </div>
        <div class="row">
            <span class="span2">Vergi No:</span><span class="span3">{{ company.vergino|default_if_none:"" }}</span>
        </div>
        <div class="row">
            <span class="span2">Tel:</span><span class="span3"><a href="tel:{{ company.phone }}">{{ company.phone }}</a></span>
        </div>
        <div class="row">
            <span class="span2">Fax:</span><span class="span3"><a href="tel:{{ company.fax }}">{{ company.fax }}</a></span>
        </div>
        <div class="row">
            <span class="span2">Limit:</span><span class="span8">{{ company.limit|tl }}</span>
        </div>
        <div class="row">
            <div class="pagination pagination-centered">
            <ul>
                {% if prev_page_no %}
                    <li><a href="?{{ queries.urlencode }}&page={{ prev_page_no}}">Önceki</a></li>
                {% else %}
                    <li class="disabled"><a href="#">Önceki</a></li>
                {% endif %}

                {% for num in paginator.page_range  %}
                    <li class="{% ifequal curr_page_no num %}active{% endifequal %}"><a href="?{{ queries.urlencode }}&page={{ num }}">{{ num }}</a></li>
                {% endfor %}

                {% if next_page_no %}
                    <li><a href="?{{ queries.urlencode }}&page={{ next_page_no}}">Sonraki</a></li>
                {% else %}
                    <li class="disabled"><a href="#">Sonraki</a></li>
                {% endif %}
            </ul>
            </div>

            <table class="table table-striped table-condensed">
                <thead>
                <tr>
                    <th style="width: 2%">No</th>
                    <th style="width: 10%">Oluşturulma</th>
                    <th class="right-aligned" style="width: 10%">Borç</th>
                    <th class="right-aligned" style="width: 10%">Alacak</th>
                    <th class="right-aligned" style="width: 10%">Toplam</th>
                    <th style="width: 5%">Tip</th>
                    <th>Not</th>
                    <th style="width: 10%">Değiştirilme</th>
                    <th style="width: 15%"></th>
                </tr>
                </thead>
                <tbody>
                {% for line in lines %}
                    <tr class="{% if line.is_cancelled %}cancelled{% endif %}">
                        <td>{{ line.no }}</td>
                        <td>
                            {{ line.created_at|date:"d/m/Y" }}
                        </td>
                        <td class="right-aligned bold">{{ line.borc|tl }}</td>
                        <td class="right-aligned bold">{{ line.alacak|tl }}</td>
                        <td class="right-aligned bold">{{ line.total|tl }}</td>
                        <td>{{ line.get_tip_display}}</td>
                        <td>{{ line.note|default_if_none:'' }}</td>
                        <td>
                            {{ line.modified_at|date:"d/m/Y" }}
                        </td>
                        <td>
                            <a class="btn" href="{% url company-line-edit line.id %}"><i class="icon-edit"></i>Düzenle</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

defter/templates/core/company_form.html
{% extends 'base.html' %}

{% block content %}
    {% if form.errors %}
        {{form.errors}}
    {% endif %}
    <form method="POST" action="{{ form.action }}" autocomplete="off">
        {% csrf_token %}
        <div class="controls controls-row">
        {{ form.name.label_tag }}
        {{ form.name }}
        </div>
        <div class="controls controls-row">
        {{ form.address.label_tag }}
        {{ form.address }}
        </div>
        <div class="controls controls-row">
            {{ form.email.label_tag }}
            {{ form.email }}
        </div>
        <div class="controls controls-row">
        {{ form.vergidairesi.label_tag }}
        {{ form.vergidairesi }}
        </div>
        <div class="controls controls-row">
        {{ form.vergino.label_tag }}
        {{ form.vergino }}
        </div>
        <div class="controls controls-row">
        {{ form.phone.label_tag }}
        {{ form.phone }}
        {{ form.fax.label_tag }}
        {{ form.fax }}
        {{ form.limit.label_tag }}
        </div>
        <div class="controls controls-row">
            <label>Limit</label>
            <input class="span2" type="text" name="limit_tam" value="{{ form.limit_tam.value|default_if_none:'0' }}" />
            <input class="span1" type="text" name="limit_kusur" value="{{ form.limit_kusur.value|default_if_none:'00' }}" />
        </div>

        <input class="btn btn-primary" type="submit" value="Kaydet"/>
        <a class="btn" href="{% url home %}">İptal</a>
    </form>
{% endblock %}

defter/templates/core/company_list.html
{% extends 'base.html' %}
{% load defter_filters %}
{% block content %}
    {% if letters %}
        {% for letter, value in letters %}
            <a class="btn" href="{% url company-list-letter letter %}">{{ value }}</a>
        {% endfor %}
    {% endif %}
    <div>
        <table class="table table-condensed table-striped">
            <thead>
                <tr>
                    <th style="width: 10%">No</th>
                    <th>Adı</th>
                    <th class="right-aligned">Borç</th>
                    <th class="right-aligned">Alacak</th>
                    <th class="right-aligned">Limit</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for company in companies %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url company-detail company.id %}">{{ company.name }}</a></td>
                    <td class="right-aligned bold">{{ company.sum_borc|tl }}</td>
                    <td class="right-aligned bold">{{ company.sum_alacak|tl }}</td>
                    <td class="right-aligned bold">{{ company.limit|tl }}</td>
                    <td>
                       <a class="btn" href="{% url company-line-create company.id %}"><i class="icon-plus"></i>Kayıt Ekle</a>
                       <a class="btn" href="{% url company-edit company.id %}"><i class="icon-edit"></i>Değiştir</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

defter/templates/core/company_query.html
{%  extends "base.html" %}
{% load defter_filters %}
{% block content %}
    <form class="form-inline" method="get" action="{% url company-query %}">
        <label for="id_start_date">Başlangıç</label>
        <input class="span2 datepicker" type="text" id="id_start_date"  name="start_date" value="{{ start_date|date:"d/m/Y" }}" />
        <label for="id_end_date">Bitiş</label>
        <input class="span2 datepicker" type="text" id="id_end_date" name="end_date" value="{{ end_date|date:"d/m/Y" }}" />
        <button class="btn btn-primary" type="submit">Filtrele</button>
    </form>
    <table class="table table-striped table-condensed">
        <thead>
        <tr>
            <td>Kullanıcı Adı</td>
            <td>Borç Toplamı</td>
            <td>Alacak Toplamı</td>
        </tr>
        </thead>
        <tbody>
        {% for line in lines %}
            <tr>
                <td>{{ line.owner }}</td>
                <td>{{ line.sum_borc|tl }}</td>
                <td>{{ line.sum_alacak|tl }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

defter/templates/core/companyline_confirm_cancel.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
    {% csrf_token %}
     <p>Bu kaydı silmek istediğine emin misiniz?</p>
        <button type="submit" class="btn btn-primary">Evet</button>
        <a class="btn" href="{% url home %}">Hayır</a>
    </form>
{% endblock %}

defter/templates/core/companyline_detail.html
{% extends 'base.html' %}
{% load defter_filters %}
{% block content %}
    {{ line.company.name }}
    Borç:{{ line.borc|tl }}
{% endblock %}

defter/templates/core/companyline_form.html
{% extends 'base.html' %}

{% block content %}
    {% if form.errors %}
        <ul>
        {% for error in form.errors %}
            <li><p class="text-error"> {{ error }}</p></li>
        {% endfor %}
        </ul>
    {% endif %}
    <form method="POST" action="{{ form.action }}" autocomplete="off">
        {% csrf_token %}
        <div class="controls controls-row">
            <label class="span2">Oluşturulma Tarihi (Gün/Ay/Yıl)</label>
            <input class="span2 datepicker" type="text" name="created_at" value="{{ form.created_at.value|date:"d/m/Y" }}" />
        </div>
        <div class="controls controls-row">
            <label class="span2">Tip</label>
            <select class="span2" name="tip">
                <option value="N">Nakit</option>
                <option value="C">Çek</option>
                <option value="S">Senet</option>
                <option value="P">Pos</option>
            </select>
        </div>
        <div class="controls controls-row">
            <label class="span2">Borç</label>
            <input class="span2" type="text" name="borc_tam" value="{{ form.borc_tam.value|default_if_none:'0' }}" />
            <input class="span1" type="text" name="borc_kusur" value="{{ form.borc_kusur.value|default_if_none:'00' }}" />
        </div>
        <div class="controls controls-row">
            <label class="span2">Alacak</label>
            <input class="span2" type="text" name="alacak_tam"  value="{{ form.alacak_tam.value|default_if_none:'0' }}"/>
            <input class="span1" type="text" name="alacak_kusur"  value="{{ form.alacak_kusur.value|default_if_none:'00' }}"/>
        </div>
        <div class="controls controls-row">
            <label class="span2">Not</label>
            <input class="span5" type="text" name="note" value="{{ form.note.value|default_if_none:"" }}" />
        </div>
        <button class="btn btn-primary" type="submit">Kaydet</button>
        <a class="btn" href="{% url company-detail company.id %}">İptal</a>
    </form>
{% endblock %}

defter/templates/core/user_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
    <form method="POST" action="{{ form.action }}" autocomplete="off">
        {% if form.errors %}
            {{ form.errors }}
        {% endif %}
        {% csrf_token %}
        <label>Kullanıcı adı</label>
        <input type="text" name="username" value="{{ form.username.value|default_if_none:'' }}"/>
        <label>Email</label>
        <input type="text" name="email" value="{{ form.email.value|default_if_none:'' }}"/>
        <label>Şifre</label>
        <input type="password" name="password1" value="{{ form.password1.value|default_if_none:'' }}"/>
        <label>Şifre (tekrar)</label>
        <input type="password" name="password2" value="{{ form.password2.value|default_if_none:'' }}"/>

        <button type="submit" class="btn btn-primary">Oluştur</button>
        <a class="btn" href="{% url home %}">İptal</a>
    </form>
    </div>
{% endblock %}